apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-csr-approver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://postfinance.github.io/kubelet-csr-approver
    chart: kubelet-csr-approver
    targetRevision: 1.2.15
    helm:
      valuesObject:
        image:
          tag: v1.2.15@sha256:6469ef517d2b6d3cb108fce8a913483533a48b1cd78b5d4af307fa09e04a7818
        providerRegex: ^jackindabox-control-plane$
        providerIpPrefixes:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - fc00::/7
        replicas: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubelet-csr-approver
        extraObjects:
          - |
            apiVersion: policy/v1
            kind: PodDisruptionBudget
            metadata:
              name: kubelet-csr-approver
              namespace: kube-system
            spec:
              minAvailable: 1
              selector:
                matchLabels:
                  app.kubernetes.io/name: kubelet-csr-approver
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
